Feature/io 421 base architecture
nikolay-ahramovich-idf/star_movie_app pull request #1
Opened 2022-09-05 10:55 UTC by nikolay-ahramovich-idf

2022-09-05 11:02 UTC, ekaterina-demeshko-idf approved these changes

2022-09-05 11:02 UTC, ekaterina-demeshko-idf commented on packages/data/.metadata
> +  revision: f1875d570e39de09040c8f79aa13cc56baab8db1
gitignore it

2022-09-05 11:02 UTC, ekaterina-demeshko-idf commented on packages/domain/.metadata
> +version:
-//-

2022-09-05 11:02 UTC, ekaterina-demeshko-idf commented on packages/presentation/.metadata
> +  channel: stable
-//-

2022-09-05 12:12 UTC, nikolay-ahramovich-idf commented on packages/data/.metadata
> +  revision: f1875d570e39de09040c8f79aa13cc56baab8db1
fixed.

2022-09-05 12:12 UTC, nikolay-ahramovich-idf commented on packages/domain/.metadata
> +version:
fixed.

2022-09-05 12:12 UTC, nikolay-ahramovich-idf commented on packages/presentation/.metadata
> +  channel: stable
fixed.

2022-09-05 16:33 UTC, sergei-mikhailovskii-idf requested changes

2022-09-05 16:33 UTC, sergei-mikhailovskii-idf commented on .gitignore
> +**/pubspec.lock
top solution!

2022-09-05 16:33 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/base/bloc.dart
> +  initState();
add return type

2022-09-05 16:33 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/base/bloc.dart
> +  void dispose();
formatting

variable
variable

method
method

2022-09-05 16:33 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/star_movie_app.dart
> +  }
need to add navigator logic

2022-09-06 08:24 UTC, nikolay-ahramovich-idf commented on packages/presentation/lib/star_movie_app.dart
> +  }
Fixed.

2022-09-06 08:24 UTC, nikolay-ahramovich-idf commented on packages/presentation/lib/bloc/base/bloc.dart
> +  void dispose();
Fixed.

2022-09-06 08:24 UTC, nikolay-ahramovich-idf commented on packages/presentation/lib/bloc/base/bloc.dart
> +  initState();
Fixed.

2022-09-06 14:04 UTC, sergei-mikhailovskii-idf approved these changes

2022-09-06 14:04 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/bloc/base/bloc.dart
> +  void add(dynamic data);
dynamic -> S

2022-09-06 14:36 UTC, nikolay-ahramovich-idf commented on packages/presentation/lib/bloc/base/bloc.dart
> +  void add(dynamic data);
Fixed.

2022-09-08 07:31 UTC, andrei-lastochkin-idf approved these changes

2022-09-08 07:32 UTC, merged