Feature/io 585 app flavors
nikolay-ahramovich-idf/star_movie_app pull request #7
Opened 2022-09-30 12:45 UTC by nikolay-ahramovich-idf

2022-09-30 14:10 UTC, ekaterina-demeshko-idf approved these changes

2022-09-30 14:10 UTC, ekaterina-demeshko-idf commented on lib/main_sandbox.dart
> +    apiBaseUrl: 'https://api-staging.trakt.tv',
maybe using one file(json, yaml) with all configurations settings is better. Don't know for sure

2022-09-30 14:10 UTC, ekaterina-demeshko-idf commented on packages/presentation/lib/screens/home/home_screen.dart
> +                  if (data.movies.isNotEmpty)
guess its better to use {} always

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf requested changes

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf commented on lib/main_sandbox.dart
> +    apiBaseUrl: 'https://api-staging.trakt.tv',
agree with @ekaterina-demeshko-idf. it will be more convenient

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf commented on packages/data/lib/repositories/trakt_movies_repository_impl.dart
> +      );
in which case do u receive exception?

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf commented on packages/domain/lib/entities/movies_response_entity.dart
> +  String? errorMessage;
I don't think it is the best solution. better to create an exception class in domain and throw its object in data layer

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/const.dart
> +      'Movies are not available due to error. Turn to administrator!';
move it into localization

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/screens/home/home_screen.dart
> +                  if (data.movies.isNotEmpty)
up to u. I also prefer brackets

2022-09-30 15:02 UTC, sergei-mikhailovskii-idf commented on packages/presentation/lib/utils/styles.dart
>  }
I don't think we need to create separate style for this text. we can use something like `white24Style`

2022-10-03 08:12 UTC, andrei-lastochkin-idf approved these changes

2022-10-06 15:47 UTC, sergei-mikhailovskii-idf approved these changes

2022-10-06 15:47 UTC, sergei-mikhailovskii-idf commented on lib/environments.dart
> +enum Environments {
```suggestion
enum Environment {
```

2022-10-06 18:46 UTC, merged